
version: 1.0.{build}
image: Visual Studio 2017
clone_depth: 1
build:
  verbosity: minimal
test:
  assemblies:
    only:
    - '**/AddressParser.Tests.dll'
artifacts:
- path: '**/AddressParser.*.nupkg'